---
- name: install pulp rpm gpg keys
  rpm_key: 
    state: present
    key: "{{ item.gpg_key_url }}"
  with_items: "{{ repos_custom_repos }}"

- name: copy pulp repo file
  template: src=etc.yum.repos.d.custom.repo.j2 dest={{ repos_location }}/custom.repo owner=root group=root mode=0644

