---
- name: Configure CentOS 7
  include_tasks:
    file: centos.yaml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'

- name: Configure Oracle Linux
  include_tasks:
    file: oraclelinux.yaml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'OracleLinux'

- name: Configure Amazon Linux 2
  include_tasks:
    file: amzn2.yaml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Amazon'

- name: Configure Custom-Included Repos
  include_tasks:
    file: customrepos.yaml
