---
- name: enable addon packages
  ini_file:
    path: "/etc/yum.repos.d/oracle-linux-ol{{ ansible_distribution_major_version }}.repo"
    section: "ol{{ ansible_distribution_major_version }}_addons"
    option: enabled
    value: "1"
    no_extra_spaces: yes
  when: repos_enable_oracle_addons

- name: enable optional packages (EL7)
  ini_file:
    path: /etc/yum.repos.d/oracle-linux-ol7.repo
    section: ol7_optional_latest
    option: enabled
    value: "1"
    no_extra_spaces: yes
  when: ansible_distribution_major_version == '7' and repos_enable_oracle_optional

- name: enable kvm utilities packages
  ini_file:
    path: "/etc/yum.repos.d/virt-ol{{ ansible_distribution_major_version }}.repo"
    section: "ol{{ ansible_distribution_major_version }}_optional_latest"
    option: enabled
    value: "1"
    no_extra_spaces: yes
  when: repos_enable_oracle_kvm

- name: install epel repo (EL6)
  yum:
    name: https://archives.fedoraproject.org/pub/archive/epel/6/x86_64/epel-release-6-8.noarch.rpm
    state: latest
    disable_excludes: all
  when: ansible_distribution_major_version == '6' and repos_enable_epel

- name: install epel repo
  yum:
    name: "oracle-epel-release-el{{ ansible_distribution_major_version }}"
    state: latest
    disable_excludes: all
  when: ansible_distribution_major_version >= '7' and repos_enable_epel

- name: install SCL repo (EL7)
  yum:
    name: oracle-softwarecollection-release-el7
    state: latest
    disable_excludes: all
  when: ansible_distribution_major_version == '7' and repos_enable_scl

